## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Chapel of MOOP"
theme = "hugo-story"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]

## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

logo = "images/chapel_logo.png"
favicon = true

[services]
  [services.googleAnalytics]
    ID = "G-R13QQH0MXH"

[params]
  description = "Chapel of MOOP"
  logo = "images/chapel_logo.png"
  favicon = true

[Params.social]
  github = "https://github.com/dmilad/chapelofmoop"
  email = "chapelofmoop@gmail.com"
  instagram = "https://instagram.com/chapelofmoop"
